import { ThemeDefinition, ThemeId } from "@/types/theme";

export const themes: Record<ThemeId, ThemeDefinition> = {
  "midnight-cinema": {
    id: "midnight-cinema",
    name: "Midnight Cinema",
    description: "Deep velvety dark backdrop with rich gold title accents & subtle film grain atmosphere.",
    fontSerifFamily: "var(--font-serif), 'Cormorant Garamond', Georgia, serif",
    fontSansFamily: "var(--font-sans), 'Plus Jakarta Sans', sans-serif",
    tokens: {
      bgPrimary: "#08090C",
      bgSecondary: "#12141A",
      bgCard: "#1A1D26",
      textPrimary: "#F5F1E8",
      textSecondary: "#A3A099",
      textAccent: "#D4AF37",
      accentPrimary: "#D4AF37",
      accentSecondary: "#C9A96E",
      accentGlow: "rgba(212, 175, 55, 0.25)",
      borderSubtle: "rgba(212, 175, 55, 0.15)",
      borderStrong: "rgba(212, 175, 55, 0.4)",
    },
    background: {
      type: "gradient",
      css: "radial-gradient(ellipse at 50% 20%, #161924 0%, #08090C 75%)",
      overlayGrain: true,
      vignette: true,
    },
    decorativeLayers: {
      showParticles: true,
      particleStyle: "gold-dust",
      glowPosition: "top-center",
    },
    motionPreset: {
      heroDurationMs: 1400,
      sceneDurationMs: 700,
      microDurationMs: 200,
      easeCurve: "cubic-bezier(0.22, 1, 0.36, 1)",
    },
    componentVariants: {
      cardStyle: "editorial",
      buttonStyle: "gold-glow",
    },
  },
  "champagne-noir": {
    id: "champagne-noir",
    name: "Champagne Noir",
    description: "Dark warm espresso charcoal with glowing champagne metallic highlights.",
    fontSerifFamily: "var(--font-serif), 'DM Serif Display', Georgia, serif",
    fontSansFamily: "var(--font-sans), 'Inter', sans-serif",
    tokens: {
      bgPrimary: "#0F0D0C",
      bgSecondary: "#181513",
      bgCard: "#241F1C",
      textPrimary: "#F7F3EB",
      textSecondary: "#A89F95",
      textAccent: "#E5C384",
      accentPrimary: "#E5C384",
      accentSecondary: "#B89659",
      accentGlow: "rgba(229, 195, 132, 0.22)",
      borderSubtle: "rgba(229, 195, 132, 0.18)",
      borderStrong: "rgba(229, 195, 132, 0.45)",
    },
    background: {
      type: "gradient",
      css: "radial-gradient(circle at 60% 10%, #201A17 0%, #0F0D0C 80%)",
      overlayGrain: true,
      vignette: true,
    },
    decorativeLayers: {
      showParticles: true,
      particleStyle: "stars",
      glowPosition: "top-right",
    },
    motionPreset: {
      heroDurationMs: 1200,
      sceneDurationMs: 650,
      microDurationMs: 180,
      easeCurve: "cubic-bezier(0.16, 1, 0.3, 1)",
    },
    componentVariants: {
      cardStyle: "bordered",
      buttonStyle: "champagne-outline",
    },
  },
  "garden-afterglow": {
    id: "garden-afterglow",
    name: "Garden Afterglow",
    description: "Romantic dusk botanical atmosphere with soft rose-gold & warm amber highlights.",
    fontSerifFamily: "var(--font-serif), 'Cormorant Garamond', Georgia, serif",
    fontSansFamily: "var(--font-sans), 'Plus Jakarta Sans', sans-serif",
    tokens: {
      bgPrimary: "#0D1310",
      bgSecondary: "#151E1A",
      bgCard: "#1E2A25",
      textPrimary: "#F4F0E8",
      textSecondary: "#9DA8A2",
      textAccent: "#D6A87C",
      accentPrimary: "#D6A87C",
      accentSecondary: "#A87C55",
      accentGlow: "rgba(214, 168, 124, 0.25)",
      borderSubtle: "rgba(214, 168, 124, 0.18)",
      borderStrong: "rgba(214, 168, 124, 0.45)",
    },
    background: {
      type: "gradient",
      css: "radial-gradient(ellipse at 50% 30%, #17241F 0%, #0D1310 80%)",
      overlayGrain: true,
      vignette: true,
    },
    decorativeLayers: {
      showParticles: true,
      particleStyle: "petals",
      glowPosition: "center",
    },
    motionPreset: {
      heroDurationMs: 1500,
      sceneDurationMs: 800,
      microDurationMs: 220,
      easeCurve: "cubic-bezier(0.25, 1, 0.5, 1)",
    },
    componentVariants: {
      cardStyle: "editorial",
      buttonStyle: "velvet",
    },
  },
  "sunset-film": {
    id: "sunset-film",
    name: "Sunset Film",
    description: "Warm cinematic twilight with copper & amber dusk glow.",
    fontSerifFamily: "var(--font-serif), 'DM Serif Display', Georgia, serif",
    fontSansFamily: "var(--font-sans), 'Inter', sans-serif",
    tokens: {
      bgPrimary: "#120C17",
      bgSecondary: "#1C1324",
      bgCard: "#261A30",
      textPrimary: "#F8F3EC",
      textSecondary: "#A89BB0",
      textAccent: "#E89D67",
      accentPrimary: "#E89D67",
      accentSecondary: "#C4743E",
      accentGlow: "rgba(232, 157, 103, 0.25)",
      borderSubtle: "rgba(232, 157, 103, 0.18)",
      borderStrong: "rgba(232, 157, 103, 0.45)",
    },
    background: {
      type: "gradient",
      css: "radial-gradient(circle at 40% 20%, #241630 0%, #120C17 80%)",
      overlayGrain: true,
      vignette: true,
    },
    decorativeLayers: {
      showParticles: true,
      particleStyle: "bubbles",
      glowPosition: "top-left",
    },
    motionPreset: {
      heroDurationMs: 1300,
      sceneDurationMs: 700,
      microDurationMs: 200,
      easeCurve: "cubic-bezier(0.22, 1, 0.36, 1)",
    },
    componentVariants: {
      cardStyle: "minimal",
      buttonStyle: "champagne-outline",
    },
  },
  "playful-confetti": {
    id: "playful-confetti",
    name: "Playful Confetti",
    description: "Sophisticated dark backdrop with festive gold, coral & teal accent highlights.",
    fontSerifFamily: "var(--font-serif), 'Cormorant Garamond', Georgia, serif",
    fontSansFamily: "var(--font-sans), 'Plus Jakarta Sans', sans-serif",
    tokens: {
      bgPrimary: "#111116",
      bgSecondary: "#1A1A22",
      bgCard: "#23232E",
      textPrimary: "#FAFAF7",
      textSecondary: "#A5A5B5",
      textAccent: "#F2B84B",
      accentPrimary: "#F2B84B",
      accentSecondary: "#E06D53",
      accentGlow: "rgba(242, 184, 75, 0.28)",
      borderSubtle: "rgba(242, 184, 75, 0.2)",
      borderStrong: "rgba(242, 184, 75, 0.5)",
    },
    background: {
      type: "gradient",
      css: "radial-gradient(ellipse at 50% 15%, #20202C 0%, #111116 80%)",
      overlayGrain: true,
      vignette: true,
    },
    decorativeLayers: {
      showParticles: true,
      particleStyle: "confetti",
      glowPosition: "top-center",
    },
    motionPreset: {
      heroDurationMs: 1100,
      sceneDurationMs: 600,
      microDurationMs: 160,
      easeCurve: "cubic-bezier(0.16, 1, 0.3, 1)",
    },
    componentVariants: {
      cardStyle: "polaroid",
      buttonStyle: "gold-glow",
    },
  },
};

export const defaultThemeId: ThemeId = "midnight-cinema";
